[accounts.outlook]
email = "kerogrammer@outlook.com"
display-name = "CEO"
default = true

backend.type = "imap"
backend.host = "outlook.office365.com"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "kerogrammer@outlook.com"
backend.auth.type = "oauth2"
backend.auth.client-id = "INSERT_CLIENT_ID_HERE"
backend.auth.auth-url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
backend.auth.token-url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.office365.com"
message.send.backend.port = 587
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "kerogrammer@outlook.com"
message.send.backend.auth.type = "oauth2"
message.send.backend.auth.client-id = "INSERT_CLIENT_ID_HERE"
message.send.backend.auth.auth-url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
message.send.backend.auth.token-url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
